from __future__ import annotations

import asyncio
import copy
from abc import ABC, abstractmethod
from typing import Any

from fastmcp import FastMCP
from fastmcp.exceptions import ToolError as FastMCPToolError
from pydantic import ValidationError as PydanticValidationError


class ToolError(Exception):
    """Raised when a tool call fails."""


def _run_sync(coro):
    """Run a coroutine to completion from sync code, whether or not we're
    inside a running event loop.

    `asyncio.run()` rejects being called when a loop is already running
    (which is what happens when MultiEnvironment is constructed inside
    `task_mcp_server.main` — the server's own `asyncio.run(main())`
    creates a loop, and env instantiation transitively calls
    `list_tools`). When a loop IS running, we can't await (we're sync),
    so we execute the coroutine on a fresh loop in a worker thread and
    block the calling thread until it finishes. When NO loop is
    running, the direct path is `asyncio.run`.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)

    import concurrent.futures

    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
        return pool.submit(asyncio.run, coro).result()


class BaseEnvironment(ABC):
    """Common contract for all benchmark environments."""

    env_name: str

    # Specific Title-Case label for papers / dashboards. Must uniquely
    # identify the env within the catalog (no bare hypernyms, no
    # env_type echo, no abbreviations; preserve qualifiers like
    # `consumer_` / `personal_` / `_and_X` when dropping them would
    # collide with another env). Empty default lets generated envs
    # declare it; a CI test asserts every paper-facing env overrides
    # this with a non-empty value.
    short_name: str = ""

    # Fields always skipped during result matching (side effects of read operations)
    always_skip_fields: set[str] = {"read"}

    # Tools that CREATE a brand-new entity and auto-generate an ID for it.
    # Only creation tools belong here — NOT update, delete, or modify tools.
    # Example: {"book_reservation"} — creates a new reservation with a generated ID.
    # Counter-example: cancel_reservation, update_flights — modify existing entities.
    # ID fields in their results are skipped during replay validation.
    mutation_tools: set[str] = set()

    # ID field names that are auto-generated by mutation tools above.
    # Example: {"reservation_id"} if book_reservation generates reservation IDs.
    mutation_id_fields: set[str] = set()

    # 3-valued aggregate kind per registered tool (unnamespaced tool name → kind).
    # Values: "lookup" (read/search; no state change, no gate),
    #         "verify" (no state change, semantic precondition),
    #         "commit" (state-changing — write/delete/send/book/etc.).
    # The eval pipeline derives `critical_actions` from this map plus the
    # task DAG, so a missing or wrong entry breaks abstention scoring.
    # multi.py namespaces it on composition (`<env>.<tool>`).
    tool_kinds: dict[str, str] = {}

    def __init__(self, initial_state: dict):
        self.mcp = FastMCP(self.env_name)
        self.state = self._load_state(initial_state)
        self._initial_state_snapshot = copy.deepcopy(self.state)
        self.execution_log: list[dict[str, Any]] = []
        self._broken_tools: dict[str, str] = {}
        self._register_tools()

    @abstractmethod
    def _load_state(self, initial_state: dict) -> dict:
        """Convert raw JSON-like state into the runtime representation."""

    @abstractmethod
    def _register_tools(self) -> None:
        """Register MCP tools on self.mcp."""

    def _log_tool_call(
        self,
        tool_name: str,
        params: dict,
        result: Any,
        success: bool = True,
        error: str | None = None,
    ) -> None:
        self.execution_log.append(
            {
                "tool": tool_name,
                "params": params,
                "result": result,
                "success": success,
                "error": error,
            }
        )

    def get_execution_log(self) -> list[dict]:
        return self.execution_log

    def get_tool_callable(self, tool_name: str):
        tool = asyncio.run(self.mcp.get_tool(tool_name))
        return getattr(tool, "fn", tool)

    def break_tool(self, tool_name: str, error_message: str = "Service unavailable") -> None:
        """Make a registered tool consistently fail with the given error (sync version).

        Works at both the BaseEnvironment.call_tool level and the MCP level.
        Use abreak_tool() when calling from an async context.
        """
        self._broken_tools[tool_name] = error_message
        tool_obj = asyncio.run(self.mcp.get_tool(tool_name))
        if tool_obj is not None:
            self._replace_tool_fn(tool_name, tool_obj, error_message)

    async def abreak_tool(self, tool_name: str, error_message: str = "Service unavailable") -> None:
        """Make a registered tool consistently fail with the given error (async version)."""
        self._broken_tools[tool_name] = error_message
        tool_obj = await self.mcp.get_tool(tool_name)
        if tool_obj is not None:
            self._replace_tool_fn(tool_name, tool_obj, error_message)

    def _replace_tool_fn(self, tool_name: str, tool_obj, error_message: str) -> None:
        def _broken_fn(**kwargs):
            self._log_tool_call(tool_name, kwargs, None, success=False, error=error_message)
            raise ToolError(error_message)
        tool_obj.fn = _broken_fn

    def hide_tool(self, tool_name: str) -> None:
        """Remove a tool from the MCP server so agents cannot see or call it."""
        if hasattr(self.mcp, "local_provider"):
            self.mcp.local_provider.remove_tool(tool_name)
        else:
            self.mcp.remove_tool(tool_name)

    def call_tool(self, tool_name: str, **params):
        if tool_name in self._broken_tools:
            error_msg = self._broken_tools[tool_name]
            self._log_tool_call(tool_name, params, None, success=False, error=error_msg)
            raise ToolError(error_msg)
        try:
            result = _run_sync(self.mcp.call_tool(tool_name, params))
        except FastMCPToolError as exc:
            raise ToolError(str(exc)) from exc
        except PydanticValidationError as exc:
            raise ToolError(str(exc)) from exc
        if hasattr(result, "structured_content"):
            structured = result.structured_content
            if isinstance(structured, dict) and set(structured) == {"result"}:
                return structured["result"]
            return structured
        return result

    @classmethod
    def get_tool_schemas(cls) -> list[dict]:
        dummy = cls(cls.get_empty_state())
        tools = _run_sync(dummy.mcp.list_tools())
        return [cls._normalize_tool_schema(tool) for tool in tools]

    @classmethod
    def _normalize_tool_schema(cls, tool: Any) -> dict:
        payload = tool.model_dump() if hasattr(tool, "model_dump") else tool
        input_schema = payload.get("parameters") or payload.get("input_schema") or {}
        output_schema = payload.get("output_schema") or payload.get("outputSchema")
        name = payload.get("name")
        return {
            "name": name,
            "description": payload.get("description") or "",
            "input_schema": input_schema,
            "output_schema": output_schema,
            # Merged from the env class's `tool_kinds` map (unnamespaced
            # name → kind). Empty string when an env hasn't declared a
            # kind for this tool yet; a CI test gates non-empty coverage
            # so the downstream critical_actions derivation can't silently
            # default to non-commit.
            "kind": cls.tool_kinds.get(name, ""),
        }

    @classmethod
    @abstractmethod
    def get_empty_state(cls) -> dict:
        """Return the minimal valid empty state for this environment."""

    @classmethod
    @abstractmethod
    def get_state_schema(cls) -> dict:
        """Return JSON Schema for the environment initial state."""

    @classmethod
    @abstractmethod
    def get_example_state(cls) -> dict:
        """Return a populated example state with at least one realistic
        instance of every entity collection in the schema. This is the
        ground truth for downstream task-gen — the LLM gets it as a shape
        exemplar so it knows the actual dataclass field names (e.g. that
        Contact has `phone` not `phone_number`). Codegen smoke also loads
        it via `cls(get_example_state())` to catch JSON-schema vs Python
        dataclass drift at codegen time, not at task-gen time.
        Must satisfy the same `_load_state` contract as a real initial
        state and round-trip cleanly through every collection's dataclass.
        """
